# Generated by Django 4.2.13 on 2024-06-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_actors_alter_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='des',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_desp',
            field=models.CharField(default='item', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user'),
        ),
    ]
