# Generated by Django 4.2.13 on 2024-06-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
